# Generated by Django 6.1.1 on 2026-09-30 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('style', models.SlugField(default='default')),
                ('authorized_keys', models.ManyToManyField(blank=True, related_name='opens_machines', to='secure.key')),
                ('keys', models.ManyToManyField(blank=True, related_name='machines', to='secure.key')),
            ],
        ),
        migrations.CreateModel(
            name='MachineApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.desktopapp')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_apps', to='machines.machine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='apps',
            field=models.ManyToManyField(blank=True, related_name='machines', through='machines.MachineApp', to='machines.desktopapp'),
        ),
        migrations.CreateModel(
            name='MachineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='machines.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='machineapp',
            constraint=models.UniqueConstraint(fields=('machine', 'app'), name='unique_machine_app'),
        ),
        migrations.AddConstraint(
            model_name='machinesession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_active_session_per_user'),
        ),
    ]
