# Generated by Django 6.1.1 on 2026-09-30 15:36

import django.db.models.deletion
import secure.access
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='requirements',
            new_name='access',
        ),
        migrations.RemoveField(
            model_name='document',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.AddField(
            model_name='document',
            name='direct_link',
            field=models.SlugField(blank=True, default='', max_length=100, validators=[wiki.models.validate_no_colon]),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.JSONField(blank=True, default=dict, validators=[secure.access.validate_requirements]),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, validators=[wiki.models.validate_no_colon]),
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[wiki.models.validate_no_colon])),
                ('visibility', models.JSONField(blank=True, default=dict, validators=[secure.access.validate_requirements])),
                ('access', models.JSONField(blank=True, default=dict, validators=[secure.access.validate_requirements])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wiki.namespace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wiki.namespace'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('namespace', 'title'), name='wiki_document_unique_in_namespace'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('namespace__isnull', True)), fields=('title',), name='wiki_document_unique_root'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('direct_link', ''), _negated=True), fields=('direct_link',), name='wiki_document_unique_direct_link'),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='wiki_namespace_unique_in_parent'),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='wiki_namespace_unique_root'),
        ),
    ]
