# Generated by Django 6.1.1 on 2026-10-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_rename_requirements_document_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='wiki_namespace_unique_slug'),
        ),
    ]
