# Generated by Django 6.1.1 on 2026-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_namespace_slug_namespace_wiki_namespace_unique_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('doc', 'Документ'), ('scan', 'Скан'), ('web', 'Веб-снапшот')], default='doc', max_length=20),
        ),
    ]
