# Generated by Django 6.1.1 on 2026-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('doc', 'Документ'), ('scan', 'Скан'), ('web', 'Веб-снапшот'), ('rec', 'Запись')], default='doc', max_length=20),
        ),
    ]
