# Generated by Django 6.1.1 on 2026-10-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('source_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('wiki_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True)),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='map.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('de_jure', models.BooleanField(default=False)),
                ('de_facto', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_provinces', to='map.country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='map.province')),
            ],
            options={
                'ordering': ['province', 'date_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='country_valid_to_gte_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('province', 'country', 'date_from'), name='unique_ownership_start'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(condition=models.Q(('de_jure', True), ('de_facto', True), _connector='OR'), name='ownership_has_jure_or_facto'),
        ),
    ]
