# Generated by Django 6.1.1 on 2026-10-05 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Формат цвета: #RRGGBB')]),
        ),
    ]
