# Generated by Django 6.1.1 on 2026-10-06 07:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_country_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Пусто - берётся название страны', max_length=128, verbose_name='Текст')),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, 'Крупная'), (2, 'Средняя'), (3, 'Малая'), (4, 'Мелкая')], default=2, verbose_name='Ранг')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='map.country')),
            ],
            options={
                'ordering': ['country', 'rank', 'id'],
            },
        ),
    ]
